/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'MachineLearning' : IDL.Null,
  'AIConcepts' : IDL.Null,
  'Database' : IDL.Null,
  'PythonBasics' : IDL.Null,
  'DataStructures' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'text' : IDL.Text,
  'maxAnswerLength' : IDL.Nat,
  'expectedKeywords' : IDL.Vec(IDL.Text),
  'minAnswerLength' : IDL.Nat,
  'category' : Category,
  'sampleBetterAnswer' : IDL.Text,
});
export const SessionId = IDL.Nat;
export const AnswerRecord = IDL.Record({
  'sentimentScore' : IDL.Nat,
  'grammarScore' : IDL.Nat,
  'feedback' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'keywordScore' : IDL.Nat,
  'questionId' : QuestionId,
  'sessionId' : SessionId,
  'answerText' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SessionSummary = IDL.Record({
  'difficulty' : Difficulty,
  'totalScore' : IDL.Nat,
  'timestamp' : Timestamp,
  'category' : Category,
  'sessionId' : SessionId,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'scoreHistory' : IDL.Vec(SessionSummary),
  'totalSessions' : IDL.Nat,
});
export const InterviewSessionPublic = IDL.Record({
  'id' : SessionId,
  'startTime' : Timestamp,
  'endTime' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'difficulty' : Difficulty,
  'questionsAttempted' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'category' : Category,
  'isComplete' : IDL.Bool,
});
export const NlpAnalysisResult = IDL.Record({
  'overallScore' : IDL.Nat,
  'grammarScore' : IDL.Nat,
  'sentiment' : IDL.Text,
  'feedback' : IDL.Text,
  'betterAnswer' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'keywordScore' : IDL.Nat,
});
export const SubmitAnswerResult = IDL.Record({
  'answerRecord' : AnswerRecord,
  'nlpResult' : NlpAnalysisResult,
});

export const idlService = IDL.Service({
  'getQuestions' : IDL.Func(
      [Category, Difficulty],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getSessionResults' : IDL.Func(
      [SessionId],
      [IDL.Opt(IDL.Vec(AnswerRecord))],
      [],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getUserSessions' : IDL.Func([], [IDL.Vec(InterviewSessionPublic)], []),
  'startSession' : IDL.Func(
      [Category, Difficulty],
      [InterviewSessionPublic],
      [],
    ),
  'submitAnswer' : IDL.Func(
      [SessionId, QuestionId, IDL.Text],
      [SubmitAnswerResult],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'MachineLearning' : IDL.Null,
    'AIConcepts' : IDL.Null,
    'Database' : IDL.Null,
    'PythonBasics' : IDL.Null,
    'DataStructures' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'difficulty' : Difficulty,
    'text' : IDL.Text,
    'maxAnswerLength' : IDL.Nat,
    'expectedKeywords' : IDL.Vec(IDL.Text),
    'minAnswerLength' : IDL.Nat,
    'category' : Category,
    'sampleBetterAnswer' : IDL.Text,
  });
  const SessionId = IDL.Nat;
  const AnswerRecord = IDL.Record({
    'sentimentScore' : IDL.Nat,
    'grammarScore' : IDL.Nat,
    'feedback' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'keywordScore' : IDL.Nat,
    'questionId' : QuestionId,
    'sessionId' : SessionId,
    'answerText' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SessionSummary = IDL.Record({
    'difficulty' : Difficulty,
    'totalScore' : IDL.Nat,
    'timestamp' : Timestamp,
    'category' : Category,
    'sessionId' : SessionId,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'scoreHistory' : IDL.Vec(SessionSummary),
    'totalSessions' : IDL.Nat,
  });
  const InterviewSessionPublic = IDL.Record({
    'id' : SessionId,
    'startTime' : Timestamp,
    'endTime' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'difficulty' : Difficulty,
    'questionsAttempted' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'category' : Category,
    'isComplete' : IDL.Bool,
  });
  const NlpAnalysisResult = IDL.Record({
    'overallScore' : IDL.Nat,
    'grammarScore' : IDL.Nat,
    'sentiment' : IDL.Text,
    'feedback' : IDL.Text,
    'betterAnswer' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'keywordScore' : IDL.Nat,
  });
  const SubmitAnswerResult = IDL.Record({
    'answerRecord' : AnswerRecord,
    'nlpResult' : NlpAnalysisResult,
  });
  
  return IDL.Service({
    'getQuestions' : IDL.Func(
        [Category, Difficulty],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getSessionResults' : IDL.Func(
        [SessionId],
        [IDL.Opt(IDL.Vec(AnswerRecord))],
        [],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getUserSessions' : IDL.Func([], [IDL.Vec(InterviewSessionPublic)], []),
    'startSession' : IDL.Func(
        [Category, Difficulty],
        [InterviewSessionPublic],
        [],
      ),
    'submitAnswer' : IDL.Func(
        [SessionId, QuestionId, IDL.Text],
        [SubmitAnswerResult],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  });
};

export const init = ({ IDL }) => { return []; };