/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerRecord {
  'sentimentScore' : bigint,
  'grammarScore' : bigint,
  'feedback' : string,
  'confidenceScore' : bigint,
  'totalScore' : bigint,
  'keywordScore' : bigint,
  'questionId' : QuestionId,
  'sessionId' : SessionId,
  'answerText' : string,
}
export type Category = { 'MachineLearning' : null } |
  { 'AIConcepts' : null } |
  { 'Database' : null } |
  { 'PythonBasics' : null } |
  { 'DataStructures' : null };
export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface InterviewSessionPublic {
  'id' : SessionId,
  'startTime' : Timestamp,
  'endTime' : [] | [Timestamp],
  'userId' : UserId,
  'difficulty' : Difficulty,
  'questionsAttempted' : bigint,
  'totalScore' : bigint,
  'category' : Category,
  'isComplete' : boolean,
}
export interface NlpAnalysisResult {
  'overallScore' : bigint,
  'grammarScore' : bigint,
  'sentiment' : string,
  'feedback' : string,
  'betterAnswer' : string,
  'confidenceScore' : bigint,
  'keywordScore' : bigint,
}
export interface Question {
  'id' : QuestionId,
  'difficulty' : Difficulty,
  'text' : string,
  'maxAnswerLength' : bigint,
  'expectedKeywords' : Array<string>,
  'minAnswerLength' : bigint,
  'category' : Category,
  'sampleBetterAnswer' : string,
}
export type QuestionId = bigint;
export type SessionId = bigint;
export interface SessionSummary {
  'difficulty' : Difficulty,
  'totalScore' : bigint,
  'timestamp' : Timestamp,
  'category' : Category,
  'sessionId' : SessionId,
}
export interface SubmitAnswerResult {
  'answerRecord' : AnswerRecord,
  'nlpResult' : NlpAnalysisResult,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'scoreHistory' : Array<SessionSummary>,
  'totalSessions' : bigint,
}
export interface _SERVICE {
  'getQuestions' : ActorMethod<[Category, Difficulty], Array<Question>>,
  'getSessionResults' : ActorMethod<[SessionId], [] | [Array<AnswerRecord>]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getUserSessions' : ActorMethod<[], Array<InterviewSessionPublic>>,
  'startSession' : ActorMethod<[Category, Difficulty], InterviewSessionPublic>,
  'submitAnswer' : ActorMethod<
    [SessionId, QuestionId, string],
    SubmitAnswerResult
  >,
  'updateUserProfile' : ActorMethod<[string], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];