/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface SessionSummary {
    difficulty: Difficulty;
    totalScore: bigint;
    timestamp: Timestamp;
    category: Category;
    sessionId: SessionId;
}
export interface SubmitAnswerResult {
    answerRecord: AnswerRecord;
    nlpResult: NlpAnalysisResult;
}
export interface NlpAnalysisResult {
    overallScore: bigint;
    grammarScore: bigint;
    sentiment: string;
    feedback: string;
    betterAnswer: string;
    confidenceScore: bigint;
    keywordScore: bigint;
}
export interface InterviewSessionPublic {
    id: SessionId;
    startTime: Timestamp;
    endTime?: Timestamp;
    userId: UserId;
    difficulty: Difficulty;
    questionsAttempted: bigint;
    totalScore: bigint;
    category: Category;
    isComplete: boolean;
}
export interface AnswerRecord {
    sentimentScore: bigint;
    grammarScore: bigint;
    feedback: string;
    confidenceScore: bigint;
    totalScore: bigint;
    keywordScore: bigint;
    questionId: QuestionId;
    sessionId: SessionId;
    answerText: string;
}
export type QuestionId = bigint;
export type SessionId = bigint;
export interface Question {
    id: QuestionId;
    difficulty: Difficulty;
    text: string;
    maxAnswerLength: bigint;
    expectedKeywords: Array<string>;
    minAnswerLength: bigint;
    category: Category;
    sampleBetterAnswer: string;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    scoreHistory: Array<SessionSummary>;
    totalSessions: bigint;
}
export enum Category {
    MachineLearning = "MachineLearning",
    AIConcepts = "AIConcepts",
    Database = "Database",
    PythonBasics = "PythonBasics",
    DataStructures = "DataStructures"
}
export enum Difficulty {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export interface backendInterface {
    getQuestions(category: Category, difficulty: Difficulty): Promise<Array<Question>>;
    getSessionResults(sessionId: SessionId): Promise<Array<AnswerRecord> | null>;
    getUserProfile(): Promise<UserProfilePublic | null>;
    getUserSessions(): Promise<Array<InterviewSessionPublic>>;
    startSession(category: Category, difficulty: Difficulty): Promise<InterviewSessionPublic>;
    submitAnswer(sessionId: SessionId, questionId: QuestionId, answerText: string): Promise<SubmitAnswerResult>;
    updateUserProfile(name: string): Promise<UserProfilePublic>;
}
import type { AnswerRecord as _AnswerRecord, Category as _Category, Difficulty as _Difficulty, InterviewSessionPublic as _InterviewSessionPublic, Question as _Question, QuestionId as _QuestionId, SessionId as _SessionId, SessionSummary as _SessionSummary, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getQuestions(arg0: Category, arg1: Difficulty): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionResults(arg0: SessionId): Promise<Array<AnswerRecord> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionResults(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionResults(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSessions(): Promise<Array<InterviewSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSessions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSessions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async startSession(arg0: Category, arg1: Difficulty): Promise<InterviewSessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_InterviewSessionPublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_InterviewSessionPublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAnswer(arg0: SessionId, arg1: QuestionId, arg2: string): Promise<SubmitAnswerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserProfile(arg0: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return from_candid_UserProfilePublic_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return from_candid_UserProfilePublic_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_InterviewSessionPublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewSessionPublic): InterviewSessionPublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SessionSummary_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionSummary): SessionSummary {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_AnswerRecord>]): Array<AnswerRecord> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    scoreHistory: Array<_SessionSummary>;
    totalSessions: bigint;
}): {
    id: UserId;
    name: string;
    scoreHistory: Array<SessionSummary>;
    totalSessions: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        scoreHistory: from_candid_vec_n16(_uploadFile, _downloadFile, value.scoreHistory),
        totalSessions: value.totalSessions
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficulty: _Difficulty;
    totalScore: bigint;
    timestamp: _Timestamp;
    category: _Category;
    sessionId: _SessionId;
}): {
    difficulty: Difficulty;
    totalScore: bigint;
    timestamp: Timestamp;
    category: Category;
    sessionId: SessionId;
} {
    return {
        difficulty: from_candid_Difficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        totalScore: value.totalScore,
        timestamp: value.timestamp,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        sessionId: value.sessionId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    startTime: _Timestamp;
    endTime: [] | [_Timestamp];
    userId: _UserId;
    difficulty: _Difficulty;
    questionsAttempted: bigint;
    totalScore: bigint;
    category: _Category;
    isComplete: boolean;
}): {
    id: SessionId;
    startTime: Timestamp;
    endTime?: Timestamp;
    userId: UserId;
    difficulty: Difficulty;
    questionsAttempted: bigint;
    totalScore: bigint;
    category: Category;
    isComplete: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.endTime)),
        userId: value.userId,
        difficulty: from_candid_Difficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        questionsAttempted: value.questionsAttempted,
        totalScore: value.totalScore,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        isComplete: value.isComplete
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    difficulty: _Difficulty;
    text: string;
    maxAnswerLength: bigint;
    expectedKeywords: Array<string>;
    minAnswerLength: bigint;
    category: _Category;
    sampleBetterAnswer: string;
}): {
    id: QuestionId;
    difficulty: Difficulty;
    text: string;
    maxAnswerLength: bigint;
    expectedKeywords: Array<string>;
    minAnswerLength: bigint;
    category: Category;
    sampleBetterAnswer: string;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        text: value.text,
        maxAnswerLength: value.maxAnswerLength,
        expectedKeywords: value.expectedKeywords,
        minAnswerLength: value.minAnswerLength,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        sampleBetterAnswer: value.sampleBetterAnswer
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MachineLearning: null;
} | {
    AIConcepts: null;
} | {
    Database: null;
} | {
    PythonBasics: null;
} | {
    DataStructures: null;
}): Category {
    return "MachineLearning" in value ? Category.MachineLearning : "AIConcepts" in value ? Category.AIConcepts : "Database" in value ? Category.Database : "PythonBasics" in value ? Category.PythonBasics : "DataStructures" in value ? Category.DataStructures : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): Difficulty {
    return "Beginner" in value ? Difficulty.Beginner : "Advanced" in value ? Difficulty.Advanced : "Intermediate" in value ? Difficulty.Intermediate : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionSummary>): Array<SessionSummary> {
    return value.map((x)=>from_candid_SessionSummary_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterviewSessionPublic>): Array<InterviewSessionPublic> {
    return value.map((x)=>from_candid_InterviewSessionPublic_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    MachineLearning: null;
} | {
    AIConcepts: null;
} | {
    Database: null;
} | {
    PythonBasics: null;
} | {
    DataStructures: null;
} {
    return value == Category.MachineLearning ? {
        MachineLearning: null
    } : value == Category.AIConcepts ? {
        AIConcepts: null
    } : value == Category.Database ? {
        Database: null
    } : value == Category.PythonBasics ? {
        PythonBasics: null
    } : value == Category.DataStructures ? {
        DataStructures: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
} {
    return value == Difficulty.Beginner ? {
        Beginner: null
    } : value == Difficulty.Advanced ? {
        Advanced: null
    } : value == Difficulty.Intermediate ? {
        Intermediate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
